<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><LangVersion>latest</LangVersion></PropertyGroup>
  <ItemGroup><Compile Include="../../src/CultureModel.cs" Link="CultureModel.cs" /><Compile Include="../../src/CultureActivity.cs" Link="CultureActivity.cs" /></ItemGroup>
</Project>
